SELECT * FROM student;
SELECT * FROM DEPARTMENT;
SELECT * FROM agents;
select * from customer;
SELECT * FROM EMPLOYEE;
SELECT * FROM company;
SELECT * FROM daysorder;
SELECT * FROM SALES;
select NAME,char_length(NAME) as LENGTHOFNAME,
TITLE, CHAR_LENGTH( TITLE) AS TITLELENGTH
FROM student;
SELECT DEPT_NAME, (DEPT_NAME) AS DEPTNAMELENGTH,
HOD_EMPLID, (HOD_EMPLID) AS IDLENGTH
FROM DEPARTMENT;
select concat_ws (" ", WORKING_AREA, PHONE_NO) AS CONTACTINFO FROM agents;
select concat_ws(" ", CUST_CITY, WORKING_AREA, CUST_COUNTRY, PHONE_NO ) AS CUSTOMERDETAILS FROM customer;
SELECT FIELD("A", "0", "0", "8") from agents;

SELECT FIND_IN_SET("A", null);
select format(PHONE_NO, );
SELECT INSERT("NEW YORK", 5, 4, "JERSEY");
SELECT instr(LAST_NAME,"d") FROM EMPLOYEE;
SELECT lcase(LAST_NAME) AS LOWERCASELASTNAME FROM EMPLOYEE;
SELECT ucase(LAST_NAME) AS UPPERCASELASTNAME FROM EMPLOYEE;
SELECT  LEFT(FIRST_NAME, 3) AS MODIFIEDFIRST, RIGHT(LAST_NAME, 5) AS MODIFIEDLEFT FROM EMPLOYEE;
SELECT right(rtrim(AGENT_CODE),3) AS CODE, LEFT(PHONE_NO, 3) AS AREACODE FROM agents;
select length(AGENT_CODE) as codelength from agents;
SELECT LENGTH(FIRST_NAME) AS LENGTHOFNAME FROM EMPLOYEE;
SELECT locate("a", LAST_NAME) AS LOCATOR FROM EMPLOYEE;
SELECT LOCATE ("S", LAST_NAME) AS LOCATOR2 FROM EMPLOYEE;
SELECT lower(NAME), lower(TITLE) FROM student;
SELECT UPPER(FIRST_NAME), UPPER(LAST_NAME) FROM EMPLOYEE;
SELECT lpad(TRIM(FIRST_NAME), 15, "MR/MRS") AS LEFTPADFIRSTNAME FROM EMPLOYEE;
SELECT RPAD(TRIM(AGENT_NAME),6, "") AS AGENTNAME FROM agents;
SELECT ltrim(FIRST_NAME) AS FIRSTNAME, LTRIM(LAST_NAME) AS LASTNAME FROM EMPLOYEE;
SELECT position("I"IN COMPANY_NAME) AS SPOSITION, position("O" IN COMPANY_CITY) AS OPOSITION FROM company;
SELECT repeat(ORD_AMOUNT,2), repeat(ADVANCE_AMOUNT, 2) FROM daysorder;
select replace("NEW YORK", "YORK", "JERSEY");
SELECT reverse(SALESMAN) FROM SALES;
SELECT reverse(PHONE_NO) FROM customer;
SELECT CONCAT(rtrim(FIRST_NAME) , " ", RTRIM(LAST_NAME)) AS FULLNAME FROM EMPLOYEE;
SELECT FIRST_NAME SPACE(4) FROM EMPLOYEE;


select strcmp(ORD_AMOUNT, ADVANCE_AMOUNT) FROM daysorder;
SELECT substring(TAX_ID, -4, 4) AS TAX_IDLASTDIGITS FROM EMPLOYEE;
SELECT  substring_index(TAX_ID, "-", 1) AS ID FROM EMPLOYEE;
DESCRIBE EMPLOYEE;

