select * from EMPLOYEE;
SELECT EMPL_ID, CONCAT (FIRST_NAME, LAST_NAME) AS FULL_NAME , EMPL_STATUS, MANAGER_EMPLID, DEPTID, SALARY, ZIPCODE, PHONE, TAX_ID, PERFORMANCE_BAND FROM EMPLOYEE
WHERE FIRST_NAME LIKE 'A%' AND LAST_NAME LIKE '%d';

SELECT * FROM SALES;
ALTER TABLE SALES
ADD 10_INCREASE int,
ADD 20_INCREASE int,
ADD 30_INCREASE int;
UPDATE SALES
SET 10_INCREASE = (1.1*SALES_AMOUNT);
UPDATE SALES
SET 20_INCREASE = (1.2*SALES_AMOUNT);
UPDATE SALES
SET 30_INCREASE = (1.3*SALES_AMOUNT);
SELECT * FROM customer;
SELECT CUST_CODE, CUST_NAME, CUST_CITY, WORKING_AREA, CUST_COUNTRY, GRADE, OPENING_AMT, RECEIVE_AMT, PAYMENT_AMT, OUTSTANDING_AMT, PHONE_NO, AGENT_CODE FROM customer
WHERE CUST_CITY LIKE 'T%' OR CUST_CITY LIKE 'B%'OR CUST_COUNTRY = 'UK' OR OPENING_AMT= RECEIVE_AMT= PAYMENT_AMT;

