DROP TABLE IF EXISTS `T7` ;
create table `T7` ( ORDER_NO INT,
CUSTOMER_NAME varchar (70),
CUSTOMER_ADDRESS VARCHAR (192),
ZIP_CODE int,
AMOUNT int,
SUPPLIER_NAME varchar (100),
ORDER_DATE datetime,
ORDER_SHIPPED datetime,
DELIVERY_DATE datetime);

DROP TABLE T;

SELECT * FROM T7;

